#############################################
# Allgemeine Parameter - !! Pflichtfelder!! #
#############################################

## Alle Namen der Openshift Objekte werden aus dem Namen der Anwendung und der Umgebung zusammengesetzt:  applicationName-applicationEnv
## Name der Anwendung.
## Beispiel - applicationName: "mypp"
applicationName:

## Name der Umgebung.
## Beispiel - applicationEnv: "dev"
applicationEnv:

## Setzt die aktiven Spring Profiles.
## Wird für die Umgebungsvariable SPRING_PROFILES_ACTIVE der Anwendung verwendet,
## siehe hier: https://git.muenchen.de/ccse/cicd/helm-template/-/blob/main/values.yaml#L61
## Beispiel - springProfilesActive: "openshift,dev,no-security"
springProfilesActive:
