{{- if .Values.build.enabled }}
{{ include "check.required.values.all" (dict "Values" .Values) }}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.applicationName }}
  labels:
    app: {{ tpl .Values.applicationLabel . }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.applicationName }}:{{ .Values.build.applicationBuildVersion }}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: {{ .Values.build.imageStreamSource }}:latest 
  postCommit: {}
  source:
    type: Binary
    binary: {}
{{- end }}
