{{ include "check.required.values.all" (dict "Values" .Values) }}
{{ include "check.required.values.deployment" (dict "Values" .Values) }}
kind: Deployment
apiVersion: apps/v1
metadata:
  {{- with .Values.deploy.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  name: {{ .Values.applicationName }}-{{ .Values.applicationEnv }}
  labels:
    app: {{ tpl .Values.applicationLabel . }}
spec:
  replicas: {{ .Values.deploy.replicas }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      deployment: {{ .Values.applicationName }}-{{ .Values.applicationEnv }}
  template:
    metadata:
      name: {{ .Values.applicationName }}-{{ .Values.applicationEnv }}
      labels:
        app: {{ tpl .Values.applicationLabel . }}
        deployment: {{ .Values.applicationName }}-{{ .Values.applicationEnv }} 
    spec:
      volumes:
        - name: cacerts-lhm
          secret:
            defaultMode: 420
            secretName: cacerts-lhm
            items:
              - key: cacerts-lhm
                path: cacerts
{{- if .Values.appdynamics.enabled }}
        - name: appd-files
          emptyDir: {}
{{- end }}
{{- if .Values.deploy.volumes }}
        {{- tpl (toYaml .Values.deploy.volumes) . | nindent 8 }}
{{- end }}
{{- if .Values.appdynamics.enabled }}
      initContainers:
        - name: appdynamics-java-agent-init-container
          resources:
            limits:
              cpu: {{ .Values.appdynamics.resources.limits.cpu }}
              memory: {{ .Values.appdynamics.resources.limits.memory }}
            requests:
              cpu: {{ .Values.appdynamics.resources.requests.cpu }}
              memory: {{ .Values.appdynamics.resources.requests.memory }}
          command:
            - cp
            - "-r"
            - /opt/appdynamics/.
            - /appd
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          imagePullPolicy: Always
          volumeMounts:
            - name: appd-files
              mountPath: /appd
          image: >-
            image-registry.openshift-image-registry.svc:5000/openshift/appdynamics-java-agent:{{ .Values.appdynamics.version }}
{{- end }}
      containers:
        - resources:
            limits:
              cpu: {{ .Values.deploy.resources.limits.cpu }}
              memory: {{ .Values.deploy.resources.limits.memory }}
            requests:
              cpu: {{ .Values.deploy.resources.requests.cpu }}
              memory: {{ .Values.deploy.resources.requests.memory }}
          readinessProbe:
            failureThreshold: {{ .Values.deploy.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.deploy.readinessProbe.httpGet.path }}
              port: {{ .Values.deploy.readinessProbe.httpGet.port }}
              scheme: {{ .Values.deploy.readinessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.deploy.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deploy.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.deploy.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deploy.readinessProbe.timeoutSeconds }}
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep {{ .Values.deploy.lifecycle.preStop.sleep }}
          name: {{ .Values.applicationName }}-{{ .Values.applicationEnv }}
          livenessProbe:
            failureThreshold: {{ .Values.deploy.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.deploy.livenessProbe.httpGet.path }}
              port: {{ .Values.deploy.livenessProbe.httpGet.port }}
              scheme: {{ .Values.deploy.livenessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.deploy.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deploy.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.deploy.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deploy.livenessProbe.timeoutSeconds }}
          startupProbe:
            httpGet:
             path: {{ .Values.deploy.startupProbe.httpGet.path }}
             port:  {{ .Values.deploy.startupProbe.httpGet.port }}
             scheme: {{ .Values.deploy.startupProbe.httpGet.scheme }}
            failureThreshold: {{ .Values.deploy.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.deploy.startupProbe.periodSeconds }}
          env:
{{- range $key, $value := ( required "Fehler" .Values.deploy.env ) }}
            - name: {{ $key }}
              value: {{ tpl ($value | quote) $ }}
{{- end }}
{{- if .Values.appdynamics.enabled }}
            - name: APPDYNAMICS_AGENT_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
{{- end }}
{{- if .Values.deploy.envWithSecrets }}
        {{- tpl (toYaml .Values.deploy.envWithSecrets) . | nindent 12 }}
{{- end }}
{{- if .Values.deploy.envWithConfigMap }}
        {{- tpl (toYaml .Values.deploy.envWithConfigMap) . | nindent 12 }}
{{- end }}
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/pki/ca-trust/extracted/java
              name: cacerts-lhm
              readOnly: true
{{- if .Values.appdynamics.enabled }}
            - name: appd-files
              mountPath: /appd
{{- end }}
{{- if .Values.deploy.volumeMounts }}
            {{- tpl (toYaml .Values.deploy.volumeMounts) . | nindent 12 }}
{{- end }}
          envFrom:
{{- if .Values.deploy.envFrom }}
        {{- tpl (toYaml .Values.deploy.envFrom) . | nindent 12 }}
{{- end }}
          image: {{ tpl .Values.deploy.image . }}
{{- if .Values.appdynamics.enabled }}
          args:
            - '-c'
            - >-
              UNIQUE_HOST_ID=$(cat /proc/self/cgroup | head -1 | awk -F '/' ' {print $NF}' | awk -F '-' '{print $2}' | cut -c 1-12) ; if [ -z $UNIQUE_HOST_ID ]; then UNIQUE_HOST_ID=$(cat /proc/self/cgroup | head -1 | awk -F '/' '{print $NF} ' | cut -c 1-12) ; fi ;
              APPDYNAMICS_AGENT_UNIQUE_HOST_ID="$UNIQUE_HOST_ID"
              /usr/local/s2i/run
          command:
            - /bin/sh
{{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 75
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
