apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.elasticsearch.secretName }}
type: Opaque
data:
  {{ .Values.secrets.elasticsearch.secretKey }}: {{ .Values.daveConfig.elasticsearch.pass | b64enc | quote }}

